---
- name: Apt
  apt:
    update_cache: true
    upgrade: 'yes'

- name: Install qemu-guest-agent
  apt:
    name: qemu-guest-agent
    state: present
    update_cache: true
  become: true

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Reboot a slow machine that might have lots of updates to apply
  ansible.builtin.reboot:
